name = "device-heartbeat-monitor"
main = "src/index.js"
compatibility_date = "2026-05-20"

[[d1_databases]]
binding = "DB"
database_name = "device-heartbeat-monitor"
database_id = "cf6e5215-eaae-4770-81e5-739ab04f299b"

[vars]
HEARTBEAT_TIMEOUT_SECONDS = "1800"

[triggers]
crons = ["*/5 * * * *"]
